### ISSUE TITLE
I've Pink Status Bar Color

### ISSUE THREAD

**Issue by fatihturan** [alexanderte/dainty-vscode#2]
Hi,

**Sometimes** status bar background color become pink when I use Dainty theme like this one:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/26871/51912980-958ce580-23e6-11e9-908c-b45e9eaaca8c.png">

Did someone else have encountered this problem before?

**Comment by alexanderte** [comment]
When no folders or workspaces are open in VS Code, the status bar is purple for the default themes. However, currently Dainty uses the inverse point of the purple color scale as the light theme status bar color. This is why it appears pink.

I see that for the default themes, the same color is used whether the theme is dark or light. I will consider doing the same with Dainty, and I’ll leave this issue open until I’ve made a decision. I don’t have any strong opinions regarding this, and any input is appreciated.

**Comment by alexanderte** [comment]
Closing this for now.
