### ISSUE TITLE
VSCode git gutter colour does not have enough contrast for many themes

### ISSUE THREAD

**Issue by krupenja** [alexanderte/dainty-vscode#3]
VSCode git gutter indicator colour does not have enough contrast for many themes, making it not very visible.

Dainty Dark:
![image](https://user-images.githubusercontent.com/26354715/53267797-f9a48000-36ec-11e9-8af7-a16ac2899a0c.png)

Dainty Ayu:
![image](https://user-images.githubusercontent.com/26354715/53268383-94ea2500-36ee-11e9-816b-9562b295fbec.png)

Dainty Mirage:
![image](https://user-images.githubusercontent.com/26354715/53268110-dfb76d00-36ed-11e9-86de-79c154dc6ad5.png)

Applies to many other themes as well.

**Comment by alexanderte** [comment]
You’re right – that is barely visible. I’ll fix it when I find the time.

**Comment by olivier-grech** [comment]
What shoudl be changed in order to fix this? I really want this fix to happen, I'm ready to do it myself.

**Comment by alexanderte** [comment]
Sorry for the delay. This has been fixed in 1.1.22, and you should get more visible indicators by updating your Dainty extension.
